# This is a basic workflow to help you get started with Actions

name: Continuous Integration

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '8.0.232'

    - name: Continuous Integration
      run: |
        echo $GITHUB_ACTIONS
        if [ "${GITHUB_ACTIONS:-false}" = "true" ]; then
          echo "Running on Github Actions"
        else
          echo "Not running on Github Actions"
        fi
        exit 1
        ./tools/install
        xvfb-run --auto-servernum ./tools/run_session
