# This is a basic workflow to help you get started with Actions

name: macOS Tests


on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build_and_test:
    runs-on: [macos-latest]
    if: github.repository == 'ml4ai/tomcat'
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '8.0.232'

    - name: Continuous Integration
      run: ./tools/install
